### ISSUE TITLE
apt-key is deprecated - update installation instructions

### ISSUE THREAD

**Issue by dregad** [Tarsnap/tarsnap#475]
Greetings,

Your [installation instructions](https://www.tarsnap.com/pkg-deb.html#initial-setup) for Ubuntu/Debian should be updated, considering that **`apt-key` is deprecated** starting with Ubuntu 20.10 [[1]], and will only be available until Debian 11 and Ubuntu 22.04.

The key should be added to `/usr/share/keyrings` instead, and the *tarsnap.list* source created with the `signed-by` option [[2]]

Regards

[1]: http://manpages.ubuntu.com/manpages/groovy/man8/apt-key.8.html
[2]: https://wiki.debian.org/DebianRepository/UseThirdParty#Sources.list_entry

**Comment by gperciva** [comment]
Thanks for the links, @dregad!  I'll start reading up on this.

**Comment by wang-songbo** [comment]
If I understood the AskUbuntu answer well, the deb package `tarsnap-archive-keyring` should also no longer install keys to `/etc/apt/trusted.gpg.d`, since keys installed there are unconditionally trusted by `apt`.

**Comment by gperciva** [comment]
Yes -- if we only want `tarsnap-archive-keyring` to function on newer distros.  The tricky thing is supporting newer distros without losing backwards compatibility.  (For example, allowing people using Ubuntu 12.04 "Precise" to keep on getting updates via `apt-get update && apt-get upgrade`.)

Note to self: documenting the current state for myself, so that I'm not trying to keep track of things purely via bookmarks.

What's the cut-off for distros?  Support for "signed-by" in `sources.list` was added in `apt-get` 1.1.exp9:
https://salsa.debian.org/apt-team/apt/-/commit/b0d408547734100bf86781615f546487ecf390d9
which was on 2015-08-18.  But we can't assume that distros released after that date are ok, because `apt-get` is a pretty fundamental part of deb-based distros, so it would make sense to be conservative about adopting a new version.

- Ubuntu 15.10 "wily" seems to use apt 1.0.10, so probably doesn't support it.  (That's based on their `Packages.bz2`; I haven't found a man-page for their sources.list, because it was a non-LTS release and was EOL'd on 2016-06-28, and Ubuntu gets rid of their non-LTS bits fairly quickly.)
- Ubuntu 16.04 "xenial" uses apt 1.2.10, and does support it: https://manpages.ubuntu.com/manpages/xenial/en/man5/sources.list.5.html
- Debian 8 "jessie" (2015-04-26) has apt 1.0.9.8.4, and does not support it:
https://manpages.debian.org/jessie/apt/sources.list.5.en.html
  (Note that jessie still has LTS for i386, amd64, armel, and armhf. https://www.debian.org/releases/jessie/)
- Debian 9 "stretch" (2017-05-17) has apt 1.4.9, and supports it:
https://manpages.debian.org/stretch/apt/sources.list.5.en.html
- I haven't checked other deb-based distros such as Mint or ElementaryOS, but the above is enough to convince me that there's a real backwards-compatibility problem.

Going forward, I'm mulling over two options:
- have two separate packages for `tarsnap-archive-keyring`; one for older distros, one for newer distros.  To maintain backwards compatibility for existing already-installed systems, I think the name would have to stay the same; so we'd be looking at something like `tarsnapnewer-archive-keyring` or `tarsnap2-archive-keyring` to stick with the expected `deriv-archive-keyring` format described on
https://wiki.debian.org/DebianRepository/UseThirdParty

  That looks a bit ugly.  (And if we went with `tarsnap2-archive-keyring`, that would be begging for confusion amongst users about whether they need `tarsnap-` or `tarsnap2-`.)

- add code to the `install:` part of the `Makefile` to figure out whether to copy the key to `/etc/apt/trusted.gpg.d/`.  I guess that we'd check
`apt-get --version | awk '/apt/ {print $2}'`
and compare that version number against 1.1.

  Of course, that gets into all the fun of comparing version strings in a `Makefile` or shell script.  GNU `sort` has a `--version-sort` option which could help there... we normally avoid non-POSIX-compatible options, but since this is aimed at only deb-based distros, it would be ok to use.  And yes, `--version-sort` is included in GNU coreutils 8.12.197, which is the version in Ubuntu 12.04 "precise", so it would be safe to use.

  PS: hmm, I just discovered `dpkg --compare-versions`, which would simply those checks.  That's supported in `precise`, so I'm cautiously optimistic that it'll work everywhere.  I'll whip up that solution.

  Another option would be to check the contents of `$(lsb_release -s -c)` and have a whitelist for specific distros... but we know that not every distro includes `lsb_release`, so that's not a safe option.

  Of course, any of those options would drag specialized code into the `tarsnap-archive-keyring`, which would be unfortunate.  When it comes to package-signing, I prefer to keep things as simple and easy-to-audit as possible.

  Fortunately, it appears that older versions of `apt-get` ignores a `signed-by=/foo` option inside `sources.list`, so we don't need to split that part of the documentation.  (Or at least, Ubuntu 12.04 precise ignores it.  I'll have to test with more distros.)

So yeah, if this was a new package, it would be easy to follow
https://wiki.debian.org/DebianRepository/UseThirdParty
and have it done.  But it gets tricky with backwards compatibility.  Not impossible, though!

**Comment by gperciva** [comment]
@dregard, @wang-songbo: we now have an updated keyring package and instructions:
https://www.tarsnap.com/pkg-deb.html#experimental

**Comment by gperciva** [comment]
Sorry for the late update; we started using the updated keyring package and instructions for the real package (not experimental) on 2021-10-21.

https://www.tarsnap.com/pkg-deb.html
